# Generated by Django 4.2 on 2024-03-09 09:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiAnalysisLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('image_path', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('success', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('message', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('class_field', models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=5, null=True)),
                ('request_timestamp', models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('response_timestamp', models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(9999999999)])),
            ],
            options={
                'db_table': 'ai_analysis_log`',
                'db_table_comment': 'AI解析ログ',
            },
        ),
    ]
