# Generated by Django 4.2 on 2024-03-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_checker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aianalysislog',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
