# Generated by Django 4.2 on 2024-03-09 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_checker', '0002_alter_aianalysislog_success'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aianalysislog',
            name='request_timestamp',
        ),
        migrations.RemoveField(
            model_name='aianalysislog',
            name='response_timestamp',
        ),
    ]
