# Generated by Django 4.2 on 2024-03-09 14:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('file_checker', '0003_remove_aianalysislog_request_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysislog',
            name='request_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='aianalysislog',
            name='response_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
